name: SkyPvP
version: "0.98.2-SNAPSHOT"
author: Masterphoenix
main: de.master.skypvp.core.bootstrap.SkyPvp
commands:
  skypvp:
    description: Der Grundcommand für das Plugin.
  npc:
    description: Grundcommand für die NPCs.
  stats:
    description: Zeige die Statistiken eines Spielers an.
